version: '3.8'

services:
  backend:
    container_name: flask-owner-service-backend
    build: .
    command: 'python main.py'
    ports:
      - 8001:5001
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    container_name: flask-owner-service-rabbitmq
    build: .
    command: python consumer.py
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db
  
  db:
    container_name: flask-owner-service-db
    image: mysql:8.0.11
    restart: always
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 33067:3306